//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhChonPhim
    {
        public int STT { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaPhim { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
