//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaChieuPhim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaChieuPhim()
        {
            this.SuatChieux = new HashSet<SuatChieu>();
        }
    
        public int MaCa { get; set; }
        public int LoaiTG { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBD { get; set; }
        public Nullable<System.TimeSpan> ThoiGianKT { get; set; }
    
        public virtual LoaiThoiGian LoaiThoiGian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuatChieu> SuatChieux { get; set; }
    }
}
