//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaVe
    {
        public string LoaiNgay { get; set; }
        public int ThoiGian { get; set; }
        public string DinhDang { get; set; }
        public Nullable<float> NguoiLon { get; set; }
        public Nullable<float> SinhVien { get; set; }
        public Nullable<float> TreEm { get; set; }
    
        public virtual LoaiThoiGian LoaiThoiGian { get; set; }
    }
}
