//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.BinhChonPhims = new HashSet<BinhChonPhim>();
            this.SuatChieux = new HashSet<SuatChieu>();
        }
    
        public int MaPhim { get; set; }
        public string TenPhim { get; set; }
        public string HangPhim { get; set; }
        public Nullable<int> NamSX { get; set; }
        public string NuocSX { get; set; }
        public string DinhDang { get; set; }
        public Nullable<int> ThoiLuong { get; set; }
        public string GioiThieu { get; set; }
        public string CacDienVien { get; set; }
        public string Trailer { get; set; }
        public string Poster { get; set; }
        public string TheLoai { get; set; }
        public Nullable<double> DiemBinhChon { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhChonPhim> BinhChonPhims { get; set; }
        public virtual TheLoaiPhim TheLoaiPhim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuatChieu> SuatChieux { get; set; }
    }
}
