//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongChieuPhim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongChieuPhim()
        {
            this.SuatChieux = new HashSet<SuatChieu>();
        }
    
        public string MaPhong { get; set; }
        public Nullable<int> SoHangGhe { get; set; }
        public Nullable<int> SoDayGhe { get; set; }
        public string TinhTrang { get; set; }
        public string KyThuat { get; set; }
        public string ThuocRap { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual RapChieuPhim RapChieuPhim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuatChieu> SuatChieux { get; set; }
    }
}
