//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapChieuPhim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RapChieuPhim()
        {
            this.PhongChieuPhims = new HashSet<PhongChieuPhim>();
        }
    
        public string MaRap { get; set; }
        public string TenRap { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SoPhongChieu { get; set; }
        public Nullable<int> ChuRap { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongChieuPhim> PhongChieuPhims { get; set; }
    }
}
