//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuatChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuatChieu()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public int MaSuatChieu { get; set; }
        public string Phong { get; set; }
        public Nullable<int> CaChieu { get; set; }
        public Nullable<int> Phim { get; set; }
        public Nullable<System.DateTime> NgayChieu { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual CaChieuPhim CaChieuPhim { get; set; }
        public virtual Phim Phim1 { get; set; }
        public virtual PhongChieuPhim PhongChieuPhim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
